pull_request_rules:
  - name: automatic merge when at least 1 review received
    conditions:
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        method: merge
  - name: delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch: {}
